/*
Create a test contactRequests document to trigger onContactRequestAlert.

Usage (PowerShell):
$env:GOOGLE_APPLICATION_CREDENTIALS = 'C:\path\to\sa.json'
node scripts/create_test_contact.js

Be careful: this writes to the live Firebase project referenced by the service account.
*/

const admin = require('firebase-admin');

async function run() {
  try {
    console.log('Initializing admin...');
    admin.initializeApp({
      credential: admin.credential.applicationDefault(),
    });
    const db = admin.firestore();

    const ts = Date.now();
    const testEmail = `smoke-contact+${ts}@example.com`;

    console.log('Creating contactRequests document for', testEmail);
    const docRef = await db.collection('contactRequests').add({
      name: 'Smoke Contact',
      email: testEmail,
      phone: '555-0101',
      subject: 'Smoke test contact',
      message: 'This is a smoke-test contact message generated by scripts/create_test_contact.js',
      submittedAt: admin.firestore.FieldValue.serverTimestamp(),
    });

    console.log('contactRequests document created id=', docRef.id);
    // Wait so the Cloud Function can trigger and process the message, then remove the
    // test document to keep the database clean. 20s is sufficient for a cold-started
    // function to run in our environment; adjust if needed.
    const deleteDelayMs = 20000;
    console.log(`Will delete test doc in ${deleteDelayMs / 1000}s to clean up.`);
    setTimeout(async () => {
      try {
        await db.collection('contactRequests').doc(docRef.id).delete();
        console.log('Deleted test contact doc id=', docRef.id);
      } catch (delErr) {
        console.error('Failed to delete test contact doc id=', docRef.id, delErr);
      }
      console.log('Done. You can now check the function logs for onContactRequestAlert.');
      process.exit(0);
    }, deleteDelayMs);
  } catch (err) {
    console.error('Failed to create test contact doc:', err);
    process.exit(2);
  }
}

run();
